CREATE SCHEMA IF NOT EXISTS default_tenant AUTHORIZATION postgres;
DROP TABLE default_tenant.PRODUCT;
CREATE TABLE IF NOT EXISTS default_tenant.PRODUCT (ID Integer NOT NULL, NAME VARCHAR(255), PRIMARY KEY (ID));
INSERT INTO default_tenant.PRODUCT VALUES( 1000, 'this product is in default_tenant');

CREATE SCHEMA IF NOT EXISTS JCConf AUTHORIZATION postgres
DROP TABLE JCConf.PRODUCT;
CREATE TABLE IF NOT EXISTS JCConf.PRODUCT (ID Integer NOT NULL, NAME VARCHAR(255), PRIMARY KEY (ID))
INSERT INTO JCConf.PRODUCT VALUES( 1000, 'this product is in JCConf');
